package use_case.save_article;

/**
 * The output boundary interface for the Save Article use case.
 *
 * <p>
 * This interface defines how the result of the save operation is passed
 * from the use case interactor to the presenter. Implementations of this
 * interface are responsible for formatting and preparing the output data
 * for the view layer.
 */
public interface SaveArticleOutputBoundary {

    /**
     * Presents the result of the save article operation.
     *
     * @param outputData the data generated by the use case after attempting to save an article,
     *                   containing any relevant information such as success status or messages
     */
    void present(SaveArticleOutputData outputData);
}

